name: flutter_chatgpt
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  countly_flutter: ^23.12.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  logging: ^1.2.0
  path_provider: ^2.1.2
  window_manager: ^0.3.7
  dart_openai: ^5.0.0
  markdown: ^7.1.1
  flutter_markdown: ^0.6.18+2
  flutter_markdown_latex:
    # path: ../flutter_markdown_latex
    git:
      ref: main
      url: https://github.com/lollipopkit/flutter_markdown_latex
  uuid: ^4.2.2
  choice: ^2.3.0
  file_picker: ^6.1.1
  share_plus: ^7.2.1
  universal_html: ^2.2.4
  flutter_highlight:
    # git:
    #   ref: master
    #   url: https://github.com/lollipopkit/highlight.dart
    #   path: flutter_highlight
    path: ../highlight.dart/flutter_highlight
  google_fonts: ^6.1.0
  intl: ^0.18.0
  url_launcher: ^6.2.3
  dio: ^5.4.0
  r_upgrade: 0.3.8+2
  webdav_client:
    git:
      ref: main
      url: https://github.com/lollipopkit/webdav_client
  icloud_storage: ^2.2.0
  screenshot: ^2.1.0
  after_layout: ^1.2.0
  flutter_math_fork: ^0.7.2
  uni_links: ^0.5.1
  uni_links_desktop: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.3.9

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
