name: flutter_chatgpt
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  countly_flutter: ^23.12.0
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  logging: ^1.2.0
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.3
  window_manager: ^0.3.7
  dart_openai: ^5.0.0
  flutter_markdown: ^0.6.18+2
  sliding_up_panel: ^2.0.0+1
  uuid: ^4.2.2
  choice: ^2.3.0
  file_picker: ^6.1.1
  share_plus: ^7.2.1
  universal_html: ^2.2.4
  flutter_highlighter: ^0.1.1
  markdown: ^7.1.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
