name: gpt_box
description: "A third-party GPT Client for OpenAI API on all platforms."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  countly_flutter: ^24.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  logging: ^1.2.0
  path_provider: ^2.1.2
  window_manager: ^0.3.7
  dart_openai: ^5.1.0
    # git:
    #   ref: main
    #   url: https://github.com/lollipopkit/dart_openai
  markdown: ^7.1.1
  flutter_markdown: ^0.6.18+2
  flutter_markdown_latex: ^0.3.0
    # path: ../flutter_markdown_latex
    # git:
    #   ref: main
    #   url: https://github.com/xushengs/flutter_markdown_latex
  choice: ^2.3.0
  file_picker: ^8.0.0+1
  share_plus: ^8.0.2
  universal_html: ^2.2.4
  flutter_highlight: # ^0.7.0
    git:
      ref: master
      url: https://github.com/lollipopkit/highlight.dart
      path: flutter_highlight
    # path: ../highlight.dart/flutter_highlight
  google_fonts: ^6.1.0
  intl: ^0.18.0
  url_launcher: ^6.2.3
  dio: ^5.4.0
  r_upgrade: 0.3.8+2
  webdav_client:
    git:
      ref: main
      url: https://github.com/lollipopkit/webdav_client
  icloud_storage: ^2.2.0
  screenshot: ^2.3.0
  after_layout: ^1.2.0
  # flutter_math_fork: ^0.7.2
  app_links: ^6.0.1
  image_picker: ^1.0.7
  audioplayers: ^6.0.0
  cross_file: ^0.3.4
  shortid: ^0.1.2
  icons_plus: ^5.0.0
  tiktoken: ^1.0.3
  win32_registry: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.3.9

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
