name: gpt_box
description: "A third-party GPT Client for OpenAI API on all platforms."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dart_openai: ^5.1.0
    # git:
    #   ref: main
    #   url: https://github.com/lollipopkit/dart_openai
  file_picker: ^8.0.0+1
  flutter_highlight: # ^0.7.0
    git:
      ref: master
      url: https://github.com/lollipopkit/highlight.dart
      path: flutter_highlight
    # path: ../highlight.dart/flutter_highlight
  google_fonts: ^6.1.0
  screenshot: ^3.0.0
  image_picker: ^1.0.7
  audioplayers: ^6.0.0
  fl_lib:
    # git:
    #   url: https://github.com/lollipopkit/fl_lib
    #   ref: dfaeb3b
    path: ../fl_lib

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.3.9

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
